config/routes.rb
# frozen_string_literal: true

Spree::Core::Engine.routes.draw do

  namespace :admin do
    resources :fulfillment_emails
  end
end

app/models/solidus_fulfillment_emails/email.rb
##
# Fulfilment Email model
#
# Holds information about a fulfillment email like subject,
# content etc.
class SolidusFulfillmentEmails::Email < ApplicationRecord
  self.table_name = 'solidus_fulfillment_emails_emails'

  # Validations
  validates :subject, presence: true
  validates :content, presence: true
  validates :bcc_to, format: { with: Devise.email_regexp }, if: lambda { |m| m.bcc_to.present? }

  ##
  # Handles replacement of variables in the email
  def content_replaced(order)
    address = order.billing_address || order.shipping_address
    replacements = {
      order_number: order.number,
      order_total: order.total,
      name: address&.name || order.email,
    }

    final_content = content
    replacements.each do |k, v|
      final_content = final_content.gsub("{{#{k}}}", v.to_s)
    end
    final_content
  end
end

app/controllers/spree/admin/fulfillment_emails_controller.rb
# frozen_string_literal: true

module Spree
  module Admin
    ##
    # Fulfillment Email Controller
    #
    # Handles the CRUD for admins for create fulfill emails.
    class FulfillmentEmailsController < ResourceController
      # We skip auto loading of resource in index to handle this our self because
      # we want to handle some sorting etc.
      skip_before_action :load_resource, only: :index

      ##
      # Index
      # 
      # Override index to handle sorting etc.
      def index
        @search = ::SolidusFulfillmentEmails::Email.accessible_by(current_ability).ransack(params[:q])
        @emails = @search.result(distinct: true).
          page(params[:page]).
          per(params[:per_page] || Spree::Config[:orders_per_page])
      end

      private 

      ##
      # Model Class
      #
      # The class to use as resource
      def model_class
        ::SolidusFulfillmentEmails::Email
      end

      ##
      # Permited Params
      #
      # The parameters needed to create new email templates
      def permitted_resource_params
        params.require(:solidus_fulfillment_emails_email).permit(:subject, :bcc_to, :send_to_admin, :send_to_customer, :content)
      end

      ##
      # Location afer save
      #
      # The location to redirect user to after an email is saved
      def location_after_save
        admin_fulfillment_emails_path
      end

      ##
      # Edit object url
      #
      # Used in views to determine the edit url of an email
      def edit_object_url(object)
        edit_admin_fulfillment_email_path(object)
      end

      ##
      # Object url
      #
      # Used in views to determine the url of an email
      def object_url(object)
        admin_fulfillment_email_path(object)
      end

    end
  end
end

app/views/spree/admin/fulfillment_emails/_form.html.erb
<div data-hook="new_email">
  <fieldset class="no-border-bottom">
    <legend><%= t('.email') %></legend>

    <div class="field">
      <%= f.label :subject %>
      <%= f.text_field :subject, class: "form-control fullwidth" %>
    </div>

    <div class="field">
      <%= f.label :bcc_to %>
      <%= f.text_field :bcc_to, class: "form-control fullwidth" %>
    </div>

    <div class="row">
      <div class="col-h3" style="margin-left: 20px">
        <div class="field">
          <%= f.label :send_to_customer %>
          <%= f.check_box :send_to_customer, class: "" %>
        </div>
      </div>
      <div class="col-3">
        <div class="field">
          <%= f.label :send_to_admin %>
          <%= f.check_box :send_to_admin, class: "" %>
        </div>
      </div>
    </div>

    <div class="field">
      <%= f.label :content %>
      <%= f.text_area :content, class: "form-control fullwidth", id: "page_body" %>
    </div>


    <% if f.object.new_record? %>
      <%= render partial: 'spree/admin/shared/new_resource_links', locals: { collection_url: admin_fulfillment_emails_path } %>
    <% else %>
      <%= render partial: 'spree/admin/shared/edit_resource_links', locals: { collection_url: admin_fulfillment_emails_path } %>
    <% end %>
  </fieldset>
</div>

app/views/spree/admin/fulfillment_emails/edit.html.erb
<% content_for(:page_title) { t('.title') } %>

<%= form_for @fulfillment_email, url: spree.admin_fulfillment_email_path(@fulfillment_email) do |f| %>
  <%= render "form", f: f %>
<% end %>

app/views/spree/admin/fulfillment_emails/index.html.erb
<% admin_breadcrumb(plural_resource_name(SolidusFulfillmentEmails::Email)) %>
<% content_for :page_actions do %>
  <li><%= link_to t('.new_fulfillment_email'), new_admin_fulfillment_email_path, class: 'btn btn-primary' %></li>
<% end %>

<% if @emails.any? %>
<table id="listing_fulfillment_emails" class="index">
    <thead>
      <tr data-hook="admin_fulfillment_emails_index_headers">
        <th><%= sort_link(@search, :subject, SolidusFulfillmentEmails::Email.human_attribute_name(:subject)) %></th>
        <th><%= sort_link(@search, :bcc_to, SolidusFulfillmentEmails::Email.human_attribute_name(:bcc_to)) %></th>
        <th><%= sort_link(@search, :send_to_customer, SolidusFulfillmentEmails::Email.human_attribute_name(:send_to_customer)) %></th>
        <th><%= sort_link(@search, :send_to_admin, SolidusFulfillmentEmails::Email.human_attribute_name(:send_to_admin)) %></th>
        <th><%= sort_link(@search, :created_at, SolidusFulfillmentEmails::Email.human_attribute_name(:created_at)) %></th>
        <th data-hook="admin_fulfillment_emails_emails_index_header_actions" class="actions"></th>
      </tr>
    </thead>
    <tbody>
      <% @emails.each do |email| %>
       <tr>
          <td><%= email.subject %></td>
          <td><%= email.bcc_to %></td>
          <td><%= email.send_to_customer %></td>
          <td><%= email.send_to_admin %></td>
          <td><%= l(email.created_at.to_date) %></td>
          <td>
            <%= link_to_edit(email, no_text: true) %>
            <%= link_to_delete(email, no_text: true) %>
          </td>
       </tr>
      <% end %>
    </tbody>
    </thead>
</table>
<% else %>
<div class="no-objects-found">
  <%= render 'spree/admin/shared/no_objects_found',
    resource: ::SolidusFulfillmentEmails::Email,
    new_resource_url: spree.new_admin_fulfillment_email_path %>
</div>
<% end %>

app/views/spree/admin/fulfillment_emails/new.html.erb
<% content_for(:page_title) { t('.title') } %>
<%= form_for @fulfillment_email, url: spree.admin_fulfillment_emails_path, class: "row" do |f| %>
  <%= render "form", f: f %>
<% end %>

app/views/spree/admin/products/_fulfillment_email_select.html.erb
<div data-hook="admin_product_form_fulfillment_email">
  <%= f.field_container :fulfillment_email do %>
    <label>
      <%= f.label :fulfillment_email_id, 'Fulfillment Email' %>
      <%= f.collection_select(:fulfillment_email_id, 
                              ::SolidusFulfillmentEmails::Email.all, 
                              :id, 
                              :subject,
                              { include_blank: t('spree.match_choices.none') }, { class: 'custom-select' }) %>
      <%= f.error_message_on :fulfillment_email_id %>
    </label>
  <% end %>
</div>